/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background/index.vue')['default']
    CircleItem: typeof import('./src/components/CircleItem/index.vue')['default']
    DateTime: typeof import('./src/components/DateTime/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FabsBtn: typeof import('./src/components/FabsBtn/index.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Hitokoto: typeof import('./src/components/Hitokoto/index.vue')['default']
    HomeModal: typeof import('./src/components/HomeModal/index.vue')['default']
    MusicTool: typeof import('./src/components/MusicTool/index.vue')['default']
    OceanWave: typeof import('./src/components/OceanWave/index.vue')['default']
    Player: typeof import('./src/components/Player/index.vue')['default']
    Weather: typeof import('./src/components/Weather/index.vue')['default']
  }
}
