/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background/index.vue')['default']
    CardItem: typeof import('./src/components/CardItem/index.vue')['default']
    CartoonButton: typeof import('./src/components/CartoonButton/index.vue')['default']
    CircleItem: typeof import('./src/components/CircleItem/index.vue')['default']
    DateTime: typeof import('./src/components/DateTime/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FabsBtn: typeof import('./src/components/FabsBtn/index.vue')['default']
    FallLeave: typeof import('./src/components/Season/FallLeave.vue')['default']
    Fog: typeof import('./src/components/Season/Fog.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Hitokoto: typeof import('./src/components/Hitokoto/index.vue')['default']
    HomeModal: typeof import('./src/components/HomeModal/index.vue')['default']
    Lantern: typeof import('./src/components/Lantern/index.vue')['default']
    MusicTool: typeof import('./src/components/MusicTool/index.vue')['default']
    OceanWave: typeof import('./src/components/OceanWave/index.vue')['default']
    Player: typeof import('./src/components/Player/index.vue')['default']
    Rain: typeof import('./src/components/Season/Rain.vue')['default']
    Scrollbar: typeof import('./src/components/Scrollbar/index.vue')['default']
    SettingButton: typeof import('./src/components/SettingButton/index.vue')['default']
    Snow: typeof import('./src/components/Season/Snow.vue')['default']
    StarSky: typeof import('./src/components/StarSky/index.vue')['default']
    Weather: typeof import('./src/components/Weather/index.vue')['default']
  }
}
