name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 可以根据您的主分支的名称进行更改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "ws_zhu@foxmail.com"
          git config --global user.name "wushengzhu"
          echo "node_modules" >> .gitignore
          git checkout --orphan gh-pages
          mv dist/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git branch -D main
          git branch -m main
          git push -f origin main:gh-pages
